spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  profiles:
    default: dev

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false



server:
  servlet:
    session:
      cookie:
        http-only: true
